### ISSUE TITLE
Container Registry

### ISSUE THREAD

**Issue by junjuew** [cmusatyalab/tpod#6]
Gitlab's container registry uses the ACL of the repository itself making the images only available for developers of a repository. Switch to a self-hosted container registry like [this](https://docs.docker.com/registry/deploying/)?

**Comment by jaharkes** [comment]
On Tue, Jun 04, 2019 at 06:50:37PM +0000, Junjue Wang wrote:
> Gitlab's container registry uses the ACL of the repository itself
> making the images only available for developers of a repository.
> Switch to a self-hosted container registry like
> [this](https://docs.docker.com/registry/deploying/)?

Or we could have a public repository that has no source just to 'host'
the containers.

**Comment by junjuew** [comment]
Ah... I was mistakenly thinking the existing tpod-container-registry repo in gitlab is already public. In fact, it's actually "internal". After changing the visibility to "public", no authentication is needed to pull exported TPOD images.
